language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
notifications:
  slack: nutella-dev:7o4cfjd4K0Y2ulxGpHdE1jG5
script: xcodebuild -workspace Nutella.xcodeproj -scheme Nutella
  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
xcode_project: Nutella.xcodeproj
